name: CI(Xray Cloud AU)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: |
        npm install
        sudo npx playwright install-deps
        npx playwright install 
    - name: Run tests
      continue-on-error: true
      run: |  
        PLAYWRIGHT_JUNIT_OUTPUT_NAME=xray-report.xml npx playwright test
    - name: Output results file
      run: |
        cat xray-report.xml
    - uses: actions/upload-artifact@v4
      if: always()
      name: Store test results
      with:
        name: playwright-test-results
        path: |
          test-results/
          xray-report.xml
    - name: Get Xray Cloud API token
      env:
        CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
      id: xray-token
      shell: bash
      run: |
        echo  ::set-output name=XRAY_TOKEN::$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": 
        \"$XRAY_CLIENT_ID\",\"client_secret\": \"$XRAY_CLIENT_SECRET\" }" https://xray.cloud.getxray.app/api/v1/authenticate| tr -d '"')
    - name: "Import results to Xray"
      shell: bash
      run: 'curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer ${{ steps.xray-token.outputs.XRAY_TOKEN }}" --data
      "xray-report.xml" "https://au.xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=COM&testPlanKey=COM-11"'


